version: 2
jobs:
  npm-publish:
    docker:
      - image: circleci/node:4.8.3
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: npm run compile
      - run:
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          command: npm publish
  github-release:
    docker:
      - image: miyajan/node-github-release:0.1.1
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: npm run build
      - run:
          command: github-release release --user miyajan --repo garoon-soap --tag ${CIRCLE_TAG}
      - run:
          command: github-release upload --user miyajan --repo garoon-soap --tag ${CIRCLE_TAG} --name garoon-soap.js --file ./build/garoon-soap.js
      - run:
          command: github-release upload --user miyajan --repo garoon-soap --tag ${CIRCLE_TAG} --name garoon-soap.min.js --file ./build/garoon-soap.min.js
workflows:
  version: 2
  build:
    jobs:
      - npm-publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      - github-release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
